## 为什么promise resolve了一个value, 最后输出的value值确是undefined

```js
const test = new MPromise((resolve, reject) => {
    setTimeout(() => {
        resolve(111);
    }, 1000);
}).then((value) => {
    console.log('then');
});

setTimeout(() => {
    console.log(test); // 一个状态为成功 值为undefined的promise对象
}, 3000)

```
如果函数没有返回值的话，默认返回的undefined, 然后在resolvePromise函数里直接 resolve（undefined

## 为什么我在catch的回调里, 打印promise, 显示状态是pending

```js
const test = new MPromise((resolve, reject) => {
    setTimeout(() => {
        reject(111);
    }, 1000);
}).catch((reason) => {
    console.log('报错' + reason);
    console.log(test) // 值为null 状态为pending的promise对象
});

setTimeout(() => {
    console.log(test); // 值为undefined 状态为fulfilled的promise对象
}, 3000)

```
因为此时的函数还没有执行完，执行完毕后 才会进resolvePromise函数里改变promise2的状态